symfonycasts_reset_password:
    # Replace symfonycasts.reset_password.fake_request_repository with the full
    # namespace of the password reset request repository after it has been created.
    # i.e. App\Repository\ResetPasswordRequestRepository
    request_password_repository: symfonycasts.reset_password.fake_request_repository
    lifetime: 3600            # durée de validité du token en secondes (1h ici)
    throttle_limit: 3         # nombre max de demandes de réinitialisation par heure
    enable_garbage_collection: true
